image: 
- Visual Studio 2017
install:
- pip install webapp2
- pip install jinja2
- pip install -q Django==1.2.4
- pip install sys.path.append("/google-cloud-sdk/platform/google_appengine")
test_script:
- python game_mech.py
- python TicTacToe.py
build: off
